In [24]:
import numpy as np
from numpy import linalg
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score

In [25]:
# We first calculate the SVD of the matrix
X = np.array([[1,1],[-1,0],[0,-1]])
X

array([[ 1,  1],
       [-1,  0],
       [ 0, -1]])

In [26]:
X_svd = np.linalg.svd(X)

In [27]:
X_svd

(array([[-8.16496581e-01, -1.66533454e-16,  5.77350269e-01],
        [ 4.08248290e-01, -7.07106781e-01,  5.77350269e-01],
        [ 4.08248290e-01,  7.07106781e-01,  5.77350269e-01]]),
 array([1.73205081, 1.        ]),
 array([[-0.70710678, -0.70710678],
        [ 0.70710678, -0.70710678]]))

In [28]:
V_transpose = X_svd[2]
V = V_transpose.T
V

array([[-0.70710678,  0.70710678],
       [-0.70710678, -0.70710678]])

In [29]:
# We now check if V is indeed the principal component
pca = PCA(n_components=2)
pca.fit(X)

PCA(n_components=2)

In [30]:
pca.components_

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [31]:
Z = pca.transform(X)
Z

array([[ 1.41421356e+00, -3.33066907e-16],
       [-7.07106781e-01, -7.07106781e-01],
       [-7.07106781e-01,  7.07106781e-01]])

In [32]:
# We now apply PCA to Iris Example
X,y = load_iris(return_X_y=True)
pca = PCA(n_components=1)
pca.fit(X)
Z = pca.transform(X)

In [36]:
model_logistics = LogisticRegression(random_state = 0, max_iter=1000).fit(Z,y)
true_values = y
predictions = model_logistics.predict(Z)
f1_score(true_values,predictions,average='weighted')

0.93999399939994